name: Build Hand Cricket App

on:
  push:
    tags:
      - "v*"    # runs whenever you push a version tag like v1.0
  workflow_dispatch:   # manual trigger

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconsole --onefile gesture_hand_cricket_advanced.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hand-cricket-windows
          path: dist/gesture_hand_cricket_advanced.exe

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile gesture_hand_cricket_advanced.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hand-cricket-linux
          path: dist/gesture_hand_cricket_advanced
